### ISSUE TITLE
Toot選択時の色を上書きできていない問題

### ISSUE THREAD

**Issue by sora0920** [sora0920/Mastodon-cocoa#1]
Mastodonは投稿を選択すると色が変化しますがこのCSSはそれを上書きできていません。
![screenshot from 2018-05-21 10-26-19](https://user-images.githubusercontent.com/28589991/40286435-dfe2083a-5ce1-11e8-8f49-8f558315c3cf.png)
これをどうにか上書きする必要があります。

**Comment by pepepper** [comment]
.focusable:focusがTLで色を変える
.focusable:focus .detailed-status,
.focusable:focus .detailed-status__action-barがWebUIでトゥートの詳細出してる所の色が変わる
![image](https://user-images.githubusercontent.com/35837918/43364542-04e1a02c-9357-11e8-8739-80761e81ad2c.png)
